### ISSUE TITLE
Not getting notifications

### ISSUE THREAD

**Issue by housemix** [Feverqwe/twiMonBot#33]
Hey, I've been using this bot for a while and always worked like a charm (Twitch Notifications).

Today, it was the first day I added youtube livestream notifications and after that I stopped getting any TWITCH notification.

Is this related?

Meanwhile, I've deleted the youtube notification to see if I can get TWITCH notifications again

**Comment by Feverqwe** [comment]
Strange bug in runtime, fixed, add crash. Thx!
 
`unhandledRejection RequestError: Error: socket hang up at new RequestError (/opt/backend/node_modules/request-promise-core/lib/errors.js:14:15) at Request.plumbing.callback (/opt/backend/node_modules/request-promise-core/lib/plumbing.js:87:29) at Request.RP$callback [as _callback] (/opt/backend/node_modules/request-promise-core/lib/plumbing.js:46:31) at self.callback (/opt/backend/node_modules/request/request.js:185:22) at Request.emit (events.js:315:20) at Request.onRequestError (/opt/backend/node_modules/request/request.js:877:8) at ClientRequest.emit (events.js:315:20) at TLSSocket.socketCloseListener (_http_client.js:443:11) at TLSSocket.emit (events.js:327:22) at net.js:673:12 at TCP.done (_tls_wrap.js:563:7) { code: 'EFATAL' }`
